"""add embeddings table and chunk meta

Revision ID: 2aa445e7cf9f
Revises: 2f5ca4ed0fe5
Create Date: 2026-07-19 20:44:08.601336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa445e7cf9f'
down_revision: Union[str, None] = '2f5ca4ed0fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Stands in for pgvector.sqlalchemy.Vector, dropped as a dependency in 0caafc246c4f
class Vector(sa.types.UserDefinedType):
    def get_col_spec(self, **kw) -> str:
        return 'vector'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector commented out, not deleted, to keep history; 0caafc246c4f drops it
    # op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('kb_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=False),
    # sa.Column('embedding', Vector(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_embeddings_chunk_id'), 'knowledge_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_knowledge_embeddings_kb_id'), 'knowledge_embeddings', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_embeddings_node_id'), 'knowledge_embeddings', ['node_id'], unique=False)
    op.add_column('knowledge_chunks', sa.Column('meta', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'meta')
    op.drop_index(op.f('ix_knowledge_embeddings_node_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_kb_id'), table_name='knowledge_embeddings')
    op.drop_index(op.f('ix_knowledge_embeddings_chunk_id'), table_name='knowledge_embeddings')
    op.drop_table('knowledge_embeddings')
    # ### end Alembic commands ###
