"""add content column to knowledge_nodes

Revision ID: 2f5ca4ed0fe5
Revises: 7f9a165b8a15
Create Date: 2026-07-19 18:00:00.507157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f5ca4ed0fe5'
down_revision: Union[str, None] = '7f9a165b8a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_nodes', sa.Column('content', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_nodes', 'content')
    # ### end Alembic commands ###
