"""add session last_message

Revision ID: 35d200f1a2ac
Revises: 6ab7f95574ca
Create Date: 2026-07-21 13:37:18.141369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35d200f1a2ac'
down_revision: Union[str, None] = '6ab7f95574ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_message')
    # ### end Alembic commands ###
