"""add sessions intercept columns

Revision ID: 51f4cd712bf5
Revises: d0234059d270
Create Date: 2026-07-17 10:43:06.157846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51f4cd712bf5'
down_revision: Union[str, None] = 'd0234059d270'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('intercepted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('sessions', sa.Column('last_intercepted_by', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('last_intercepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'last_intercepted_at')
    op.drop_column('sessions', 'last_intercepted_by')
    op.drop_column('sessions', 'intercepted')
    # ### end Alembic commands ###
