"""add session priority and status_flags

Revision ID: 6ab7f95574ca
Revises: 2aa445e7cf9f
Create Date: 2026-07-21 10:48:52.269795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6ab7f95574ca'
down_revision: Union[str, None] = '2aa445e7cf9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('priority', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sessions', sa.Column('status_flags', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.create_index(op.f('ix_sessions_priority'), 'sessions', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_priority'), table_name='sessions')
    op.drop_column('sessions', 'status_flags')
    op.drop_column('sessions', 'priority')
    # ### end Alembic commands ###
