"""add message feedback and session vote counters

Revision ID: 7f9a165b8a15
Revises: 51f4cd712bf5
Create Date: 2026-07-17 16:40:10.010677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9a165b8a15'
down_revision: Union[str, None] = '51f4cd712bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('feedback', sa.String(), nullable=True))
    op.add_column('sessions', sa.Column('upvotes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('sessions', sa.Column('downvotes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'downvotes')
    op.drop_column('sessions', 'upvotes')
    op.drop_column('messages', 'feedback')
    # ### end Alembic commands ###
