"""add retrieval indexes

Revision ID: a93aa38c3cca
Revises: 0bd39d9f5964
Create Date: 2026-07-23 11:00:27.389912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a93aa38c3cca'
down_revision: Union[str, None] = '0bd39d9f5964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_chunks_node_id', table_name='knowledge_chunks')
    op.create_index('ix_knowledge_chunks_node_id_seq', 'knowledge_chunks', ['node_id', 'seq'], unique=False)
    op.create_index('ix_knowledge_nodes_status', 'knowledge_nodes', ['status'], unique=False)
    op.create_index('ix_knowledge_nodes_type', 'knowledge_nodes', ['type'], unique=False)
    op.drop_index('ix_messages_session_id', table_name='messages')
    op.create_index('ix_messages_session_id_created_at', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_index('ix_sessions_attention', 'sessions', ['priority', 'created_at'], unique=False, postgresql_where=sa.text("status = 'active' AND intercepted = false"))
    op.create_index('ix_sessions_created_at', 'sessions', ['created_at'], unique=False)
    # ### end Alembic commands ###

    # pgvector commented out, not deleted, to keep history; 0caafc246c4f drops it
    # op.execute(
    #     'CREATE INDEX ix_knowledge_embeddings_embedding_hnsw '
    #     'ON knowledge_embeddings USING hnsw '
    #     '((embedding::vector(1024)) vector_cosine_ops)'
    # )
    op.execute(
        "CREATE INDEX ix_knowledge_embeddings_content_fts "
        "ON knowledge_embeddings USING gin (to_tsvector('english', content))"
    )


def downgrade() -> None:
    op.execute('DROP INDEX IF EXISTS ix_knowledge_embeddings_content_fts')
    op.execute('DROP INDEX IF EXISTS ix_knowledge_embeddings_embedding_hnsw')

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessions_created_at', table_name='sessions')
    op.drop_index('ix_sessions_attention', table_name='sessions', postgresql_where=sa.text("status = 'active' AND intercepted = false"))
    op.drop_index('ix_messages_session_id_created_at', table_name='messages')
    op.create_index('ix_messages_session_id', 'messages', ['session_id'], unique=False)
    op.drop_index('ix_knowledge_nodes_type', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_status', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_chunks_node_id_seq', table_name='knowledge_chunks')
    op.create_index('ix_knowledge_chunks_node_id', 'knowledge_chunks', ['node_id'], unique=False)
    # ### end Alembic commands ###
