"""add knowledge base, node, chunk tables

Revision ID: e97702b50038
Revises: f8b035c7d13b
Create Date: 2026-07-16 13:47:16.828761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97702b50038'
down_revision: Union[str, None] = 'f8b035c7d13b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_bases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_bases_name'), 'knowledge_bases', ['name'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('kb_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('storage_key', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'parent_id', 'name', name='uq_node_name')
    )
    op.create_index(op.f('ix_knowledge_nodes_kb_id'), 'knowledge_nodes', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_parent_id'), 'knowledge_nodes', ['parent_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('kb_id', sa.String(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunks_kb_id'), 'knowledge_chunks', ['kb_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_node_id'), 'knowledge_chunks', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunks_node_id'), table_name='knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_chunks_kb_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_nodes_parent_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_kb_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_bases_name'), table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    # ### end Alembic commands ###
